name: E2E Tests

on:
  workflow_call:

jobs:
  tests:
    name: ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: mingw-w64-x86_64-gcc make git expect
          path-type: inherit

      - if: runner.os == 'Linux'
        run: |
          make clean
          bash app/tests/e2e/e2e.sh san=thread

      - if: runner.os == 'Linux'
        continue-on-error: true
        run: |
          make clean
          bash app/tests/e2e/e2e.sh san=asan

      - run: |
          make clean
          bash app/tests/e2e/e2e.sh
        shell: bash
