name: Fastchess

on:
  push:
    tags:
      - "v*"
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  Artifacts:
    if: github.ref == 'refs/heads/master' || github.ref_type == 'tag'
    uses: ./.github/workflows/artifacts.yml
  Precreate-Release:
    needs: [Artifacts]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Release
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
        if: github.ref_type == 'tag'
        with:
          draft: true
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}

  Release:
    if: github.ref_type == 'tag'
    needs: [Precreate-Release]
    permissions:
      contents: write
    uses: ./.github/workflows/release.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  E2E-Tests:
    if: github.ref_type != 'tag'
    uses: ./.github/workflows/e2e_tests.yml
  Unit-Tests:
    if: github.ref_type != 'tag'
    uses: ./.github/workflows/unit_tests.yml
  Cutechess-Tests:
    if: github.ref_type != 'tag'
    uses: ./.github/workflows/cutechess_tests.yml
